[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "buttonless"
opacity = 0.6
blur = true
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 20

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[env]
TERM = "screen-256color"
